/*
 * Dependency-Track API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 4.10.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type DependencyGraphResponse struct {
	Uuid string `json:"uuid,omitempty"`
	Name string `json:"name,omitempty"`
	Version string `json:"version,omitempty"`
	Purl string `json:"purl,omitempty"`
	DirectDependencies string `json:"directDependencies,omitempty"`
	LatestVersion string `json:"latestVersion,omitempty"`
}
