/*
 * Dependency-Track API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 4.10.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type FormDataContentDisposition struct {
	Type_ string `json:"type,omitempty"`
	Parameters map[string]string `json:"parameters,omitempty"`
	FileName string `json:"fileName,omitempty"`
	CreationDate time.Time `json:"creationDate,omitempty"`
	ModificationDate time.Time `json:"modificationDate,omitempty"`
	ReadDate time.Time `json:"readDate,omitempty"`
	Size int64 `json:"size,omitempty"`
	Name string `json:"name,omitempty"`
}
