/*
 * Dependency-Track API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 4.10.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Finding struct {
	Component map[string]interface{} `json:"component,omitempty"`
	Vulnerability map[string]interface{} `json:"vulnerability,omitempty"`
	Analysis map[string]interface{} `json:"analysis,omitempty"`
	Attribution map[string]interface{} `json:"attribution,omitempty"`
	Matrix string `json:"matrix,omitempty"`
}
