/*
 * Dependency-Track API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 4.10.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ProjectMetadata struct {
	Supplier *OrganizationalEntity `json:"supplier,omitempty"`
	Authors []OrganizationalContact `json:"authors,omitempty"`
}
