/*
 * Dependency-Track API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 4.10.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type PackageUrl struct {
	Scheme string `json:"scheme,omitempty"`
	Type_ string `json:"type,omitempty"`
	Namespace string `json:"namespace,omitempty"`
	Name string `json:"name,omitempty"`
	Version string `json:"version,omitempty"`
	Qualifiers map[string]string `json:"qualifiers,omitempty"`
	Subpath string `json:"subpath,omitempty"`
	Coordinates string `json:"coordinates,omitempty"`
}
