/*
 * Dependency-Track API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 4.10.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type RepositoryMetaComponent struct {
	RepositoryType string `json:"repositoryType"`
	Namespace string `json:"namespace,omitempty"`
	Name string `json:"name"`
	LatestVersion string `json:"latestVersion"`
	Published time.Time `json:"published,omitempty"`
	LastCheck time.Time `json:"lastCheck"`
}
