/*
 * Dependency-Track API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 4.10.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type MediaType struct {
	Type_ string `json:"type,omitempty"`
	Subtype string `json:"subtype,omitempty"`
	Parameters map[string]string `json:"parameters,omitempty"`
	WildcardType bool `json:"wildcardType,omitempty"`
	WildcardSubtype bool `json:"wildcardSubtype,omitempty"`
}
