/*
 * Dependency-Track API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 4.10.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type LicenseGroup struct {
	Name string `json:"name,omitempty"`
	Licenses []License `json:"licenses,omitempty"`
	RiskWeight int32 `json:"riskWeight,omitempty"`
	Uuid string `json:"uuid"`
}
