/*
 * Dependency-Track API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 4.10.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type ViolationAnalysisComment struct {
	Timestamp time.Time `json:"timestamp"`
	Comment string `json:"comment"`
	Commenter string `json:"commenter,omitempty"`
}
