/*
 * Dependency-Track API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 4.10.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type PolicyViolation struct {
	Type_ string `json:"type,omitempty"`
	Project *Project `json:"project,omitempty"`
	Component *Component `json:"component,omitempty"`
	PolicyCondition *PolicyCondition `json:"policyCondition,omitempty"`
	Timestamp time.Time `json:"timestamp,omitempty"`
	Text string `json:"text,omitempty"`
	Analysis *ViolationAnalysis `json:"analysis,omitempty"`
	Uuid string `json:"uuid"`
}
