/*
 * Dependency-Track API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 4.10.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type UserPrincipal struct {
	Name string `json:"name,omitempty"`
	Permissions []Permission `json:"permissions,omitempty"`
	Id int64 `json:"id,omitempty"`
	Teams []Team `json:"teams,omitempty"`
	Username string `json:"username,omitempty"`
	Email string `json:"email,omitempty"`
}
