/*
 * Dependency-Track API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 4.10.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Repository struct {
	Type_ string `json:"type"`
	Identifier string `json:"identifier,omitempty"`
	Url string `json:"url,omitempty"`
	ResolutionOrder int32 `json:"resolutionOrder"`
	Enabled bool `json:"enabled"`
	Internal bool `json:"internal"`
	AuthenticationRequired bool `json:"authenticationRequired,omitempty"`
	Username string `json:"username,omitempty"`
	Uuid string `json:"uuid"`
}
