/*
 * Dependency-Track API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 4.10.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Framework struct {
	Name string `json:"name,omitempty"`
	Version string `json:"version,omitempty"`
	Timestamp string `json:"timestamp,omitempty"`
	Uuid string `json:"uuid,omitempty"`
}
