/*
 * Dependency-Track API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 4.10.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ViolationAnalysisRequest struct {
	Component string `json:"component"`
	PolicyViolation string `json:"policyViolation"`
	AnalysisState string `json:"analysisState,omitempty"`
	Comment string `json:"comment,omitempty"`
	Suppressed bool `json:"suppressed,omitempty"`
}
