/*
 * Dependency-Track API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 4.10.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Policy struct {
	Name string `json:"name,omitempty"`
	Operator string `json:"operator,omitempty"`
	ViolationState string `json:"violationState,omitempty"`
	PolicyConditions []PolicyCondition `json:"policyConditions,omitempty"`
	Projects []Project `json:"projects,omitempty"`
	Tags []Tag `json:"tags,omitempty"`
	Uuid string `json:"uuid"`
	IncludeChildren bool `json:"includeChildren,omitempty"`
	Global bool `json:"global,omitempty"`
}
