/*
 * Dependency-Track API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 4.10.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type AffectedComponent struct {
	IdentityType string `json:"identityType,omitempty"`
	Identity string `json:"identity,omitempty"`
	VersionType string `json:"versionType,omitempty"`
	Version string `json:"version,omitempty"`
	VersionEndExcluding string `json:"versionEndExcluding,omitempty"`
	VersionEndIncluding string `json:"versionEndIncluding,omitempty"`
	VersionStartExcluding string `json:"versionStartExcluding,omitempty"`
	VersionStartIncluding string `json:"versionStartIncluding,omitempty"`
	Uuid string `json:"uuid,omitempty"`
	AffectedVersionAttributions []AffectedVersionAttribution `json:"affectedVersionAttributions,omitempty"`
}
