/*
 * Dependency-Track API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 4.10.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ProjectMetrics struct {
	Project *Project `json:"project"`
	Critical int32 `json:"critical"`
	High int32 `json:"high"`
	Medium int32 `json:"medium"`
	Low int32 `json:"low"`
	Unassigned int32 `json:"unassigned,omitempty"`
	Vulnerabilities int64 `json:"vulnerabilities,omitempty"`
	VulnerableComponents int32 `json:"vulnerableComponents,omitempty"`
	Components int32 `json:"components,omitempty"`
	Suppressed int32 `json:"suppressed,omitempty"`
	FindingsTotal int32 `json:"findingsTotal,omitempty"`
	FindingsAudited int32 `json:"findingsAudited,omitempty"`
	FindingsUnaudited int32 `json:"findingsUnaudited,omitempty"`
	InheritedRiskScore float64 `json:"inheritedRiskScore,omitempty"`
	PolicyViolationsFail int32 `json:"policyViolationsFail,omitempty"`
	PolicyViolationsWarn int32 `json:"policyViolationsWarn,omitempty"`
	PolicyViolationsInfo int32 `json:"policyViolationsInfo,omitempty"`
	PolicyViolationsTotal int32 `json:"policyViolationsTotal,omitempty"`
	PolicyViolationsAudited int32 `json:"policyViolationsAudited,omitempty"`
	PolicyViolationsUnaudited int32 `json:"policyViolationsUnaudited,omitempty"`
	PolicyViolationsSecurityTotal int32 `json:"policyViolationsSecurityTotal,omitempty"`
	PolicyViolationsSecurityAudited int32 `json:"policyViolationsSecurityAudited,omitempty"`
	PolicyViolationsSecurityUnaudited int32 `json:"policyViolationsSecurityUnaudited,omitempty"`
	PolicyViolationsLicenseTotal int32 `json:"policyViolationsLicenseTotal,omitempty"`
	PolicyViolationsLicenseAudited int32 `json:"policyViolationsLicenseAudited,omitempty"`
	PolicyViolationsLicenseUnaudited int32 `json:"policyViolationsLicenseUnaudited,omitempty"`
	PolicyViolationsOperationalTotal int32 `json:"policyViolationsOperationalTotal,omitempty"`
	PolicyViolationsOperationalAudited int32 `json:"policyViolationsOperationalAudited,omitempty"`
	PolicyViolationsOperationalUnaudited int32 `json:"policyViolationsOperationalUnaudited,omitempty"`
	FirstOccurrence float32 `json:"firstOccurrence"`
	LastOccurrence float32 `json:"lastOccurrence"`
}
