/*
 * Dependency-Track API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 4.10.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type ManagedUser struct {
	Username string `json:"username,omitempty"`
	LastPasswordChange time.Time `json:"lastPasswordChange"`
	Fullname string `json:"fullname,omitempty"`
	Email string `json:"email,omitempty"`
	Suspended bool `json:"suspended,omitempty"`
	ForcePasswordChange bool `json:"forcePasswordChange,omitempty"`
	NonExpiryPassword bool `json:"nonExpiryPassword,omitempty"`
	Teams []Team `json:"teams,omitempty"`
	Permissions []Permission `json:"permissions,omitempty"`
	NewPassword string `json:"newPassword,omitempty"`
	ConfirmPassword string `json:"confirmPassword,omitempty"`
}
