/*
 * Dependency-Track API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 4.10.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ServiceComponent struct {
	Provider *OrganizationalEntity `json:"provider,omitempty"`
	Group string `json:"group,omitempty"`
	Name string `json:"name,omitempty"`
	Version string `json:"version,omitempty"`
	Description string `json:"description,omitempty"`
	Endpoints []string `json:"endpoints,omitempty"`
	Authenticated bool `json:"authenticated,omitempty"`
	CrossesTrustBoundary bool `json:"crossesTrustBoundary,omitempty"`
	Data []DataClassification `json:"data,omitempty"`
	ExternalReferences []ExternalReference `json:"externalReferences,omitempty"`
	Parent *ServiceComponent `json:"parent,omitempty"`
	Children []ServiceComponent `json:"children,omitempty"`
	Vulnerabilities []Vulnerability `json:"vulnerabilities,omitempty"`
	Project *Project `json:"project"`
	LastInheritedRiskScore float64 `json:"lastInheritedRiskScore,omitempty"`
	Notes string `json:"notes,omitempty"`
	Uuid string `json:"uuid"`
	BomRef string `json:"bomRef,omitempty"`
}
