/*
 * Dependency-Track API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 4.10.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type FindingAttribution struct {
	AttributedOn time.Time `json:"attributedOn"`
	AnalyzerIdentity string `json:"analyzerIdentity,omitempty"`
	Component *Component `json:"component"`
	Vulnerability *Vulnerability `json:"vulnerability"`
	AlternateIdentifier string `json:"alternateIdentifier,omitempty"`
	ReferenceUrl string `json:"referenceUrl,omitempty"`
	Uuid string `json:"uuid"`
}
