/*
 * Dependency-Track API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 4.10.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type BomSubmitRequest struct {
	Project string `json:"project"`
	ProjectName string `json:"projectName,omitempty"`
	ProjectVersion string `json:"projectVersion,omitempty"`
	AutoCreate bool `json:"autoCreate,omitempty"`
	ParentUUID string `json:"parentUUID,omitempty"`
	ParentName string `json:"parentName,omitempty"`
	ParentVersion string `json:"parentVersion,omitempty"`
	Bom string `json:"bom"`
}
