/*
 * Dependency-Track API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 4.10.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type License struct {
	LicenseGroups []LicenseGroup `json:"licenseGroups,omitempty"`
	Uuid string `json:"uuid"`
	Name string `json:"name,omitempty"`
	LicenseText string `json:"licenseText,omitempty"`
	StandardLicenseTemplate string `json:"standardLicenseTemplate,omitempty"`
	StandardLicenseHeader string `json:"standardLicenseHeader,omitempty"`
	LicenseComments string `json:"licenseComments,omitempty"`
	LicenseId string `json:"licenseId,omitempty"`
	IsOsiApproved bool `json:"isOsiApproved,omitempty"`
	IsFsfLibre bool `json:"isFsfLibre,omitempty"`
	IsDeprecatedLicenseId bool `json:"isDeprecatedLicenseId,omitempty"`
	IsCustomLicense bool `json:"isCustomLicense,omitempty"`
	SeeAlso []string `json:"seeAlso,omitempty"`
}
