/*
 * Dependency-Track API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 4.10.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ExternalReference struct {
	Type_ string `json:"type,omitempty"`
	Url string `json:"url,omitempty"`
	Comment string `json:"comment,omitempty"`
}
